# Generated by Django 5.0 on 2024-01-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_amount', models.AutoField(primary_key=True, serialize=False)),
                ('item_sku', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.PositiveIntegerField()),
                ('current_item_quantity', models.PositiveIntegerField()),
                ('minimum_item_quantity', models.PositiveIntegerField()),
                ('desired_item_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
