# Generated by Django 5.0 on 2024-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockTracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_amount',
            new_name='item_id',
        ),
    ]
